// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaAPI.Model;

namespace PizzaAPI.Migrations
{
    [DbContext(typeof(PizzaDbContext))]
    partial class PizzaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PizzaAPI.Model.Crust", b =>
                {
                    b.Property<int>("CrustId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CrustName");

                    b.Property<double>("Price");

                    b.HasKey("CrustId");

                    b.ToTable("Crust");
                });

            modelBuilder.Entity("PizzaAPI.Model.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("AptNo");

                    b.Property<string>("City");

                    b.Property<int?>("PaymentId");

                    b.Property<string>("PhoneNo");

                    b.Property<string>("State");

                    b.Property<string>("Zip");

                    b.HasKey("CustomerId");

                    b.HasIndex("PaymentId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("PizzaAPI.Model.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CustomerId");

                    b.Property<DateTime>("OrderDate");

                    b.Property<double>("TotalPrice");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("PizzaAPI.Model.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CVV");

                    b.Property<string>("CardNo");

                    b.Property<string>("Expiration");

                    b.HasKey("PaymentId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("PizzaAPI.Model.Pizza", b =>
                {
                    b.Property<int>("PizzaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CrustId");

                    b.Property<DateTime>("OrderDate");

                    b.Property<int?>("OrderId");

                    b.Property<string>("PizzaName");

                    b.Property<int?>("SauceId");

                    b.Property<int?>("SizeId");

                    b.Property<int?>("Topping1ToppingId");

                    b.Property<int?>("Topping2ToppingId");

                    b.Property<int?>("Topping3ToppingId");

                    b.Property<double>("Total");

                    b.HasKey("PizzaId");

                    b.HasIndex("CrustId");

                    b.HasIndex("OrderId");

                    b.HasIndex("SauceId");

                    b.HasIndex("SizeId");

                    b.HasIndex("Topping1ToppingId");

                    b.HasIndex("Topping2ToppingId");

                    b.HasIndex("Topping3ToppingId");

                    b.ToTable("Pizza");
                });

            modelBuilder.Entity("PizzaAPI.Model.Sauce", b =>
                {
                    b.Property<int>("SauceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SauceName");

                    b.HasKey("SauceId");

                    b.ToTable("Sauce");
                });

            modelBuilder.Entity("PizzaAPI.Model.Size", b =>
                {
                    b.Property<int>("SizeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Price");

                    b.Property<string>("SizeName");

                    b.HasKey("SizeId");

                    b.ToTable("Size");
                });

            modelBuilder.Entity("PizzaAPI.Model.Topping", b =>
                {
                    b.Property<int>("ToppingId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Price");

                    b.Property<string>("ToppingName");

                    b.HasKey("ToppingId");

                    b.ToTable("Topping");
                });

            modelBuilder.Entity("PizzaAPI.Model.Customer", b =>
                {
                    b.HasOne("PizzaAPI.Model.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId");
                });

            modelBuilder.Entity("PizzaAPI.Model.Order", b =>
                {
                    b.HasOne("PizzaAPI.Model.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("PizzaAPI.Model.Pizza", b =>
                {
                    b.HasOne("PizzaAPI.Model.Crust", "Crust")
                        .WithMany()
                        .HasForeignKey("CrustId");

                    b.HasOne("PizzaAPI.Model.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.HasOne("PizzaAPI.Model.Sauce", "Sauce")
                        .WithMany()
                        .HasForeignKey("SauceId");

                    b.HasOne("PizzaAPI.Model.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId");

                    b.HasOne("PizzaAPI.Model.Topping", "Topping1")
                        .WithMany()
                        .HasForeignKey("Topping1ToppingId");

                    b.HasOne("PizzaAPI.Model.Topping", "Topping2")
                        .WithMany()
                        .HasForeignKey("Topping2ToppingId");

                    b.HasOne("PizzaAPI.Model.Topping", "Topping3")
                        .WithMany()
                        .HasForeignKey("Topping3ToppingId");
                });
#pragma warning restore 612, 618
        }
    }
}
